IoT_Dash/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dash.urls'))
]

dash/urls.py
from django.urls import path
from . import views

app_name = 'dash'

urlpatterns = [
    
    #Sensor
    path('sensor/create/', views.sensor_create, name='sensor_create'),
    path('sensor/dashboard/', views.sensor_dashboard, name='sensor_dashboard'),
    path('sensor/view/', views.sensor_view, name='sensor_view'),
    path('sensor/edit/', views.sensor_edit, name='sensor_edit'),
    path('sensor/delete/', views.sensor_delete, name='sensor_delete'),
    path('sensor/data/', views.sensor_data, name='sensor_data'),
    path('sensor/data/get/', views.sensor_get, name='sensor_get'),

    #Sensor Group
    path('group/create/', views.group_create, name='group_create'),
    path('group/dashboard/', views.group_dashboard, name='group_dashboard'),
    path('group/view/', views.group_view, name='group_view'),
    path('group/edit/', views.group_edit, name='group_edit'),
    path('group/delete/', views.group_delete, name='group_delete'),
    
    #Login/Logout
    path('logout/', views.logout_user, name='logout_user'),
    path('', views.login_user, name='login'),

    # Download data
    path('download_data/<str:file_format>/<str:sensor_key>/', views.download_data, name='download_data'),
    path('download_group_data/<str:file_format>/<str:group_id>/', views.download_group_data, name='download_group_data'),
]

templates/view/group_view.html
{% extends 'base.html' %}

{% block content %}
<div class="m-5">
    {% if messages %}
        <div class="mx-auto alerts">

            {% for message in messages %}
                {% if message.tags == "error" %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% elif message.tags == "info" %}
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% endif %}
            {% endfor %}

        </div>
    {% endif %}
    <form id="main_form" method="POST">
        {% csrf_token %}
        <span class="fs-2 p-2">Sensor Group Details</span>
        
        <hr>
        <div class="d-flex flex-column m-3 p-3">
            <div class="d-flex flex-row flex-fill">
                <div class="m-3 flex-fill">
                    <label class="form-label fs-5" for="{{form.group_name.id_for_label}}">Sensor Group Name</label>
                    {{form.group_name}}
                </div>
            
                <div class="m-3 flex-fill">
                    <label class="form-label fs-5" for="{{form.group_type.id_for_label}}">Sensor Group Type</label>
                    {{form.group_type}}
                </div>
            </div>
            <div class="d-flex flex-row flex-fill">
                <div class="m-3 flex-fill">
                    <label class="form-label fs-5" for="{{form.group_discription.id_for_label}}">Sensor Group Description</label>
                    {{form.group_discription}}
                </div>
            </div>
        </div>
    </form>
    <div class="d-flex flex-row mt-4 ms-3">
        <div class="btn-group">
            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                Download Data
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'dash:download_group_data' 'csv' group_id%}">CSV</a></li>
                <li><a class="dropdown-item" href="{% url 'dash:download_group_data' 'txt' group_id%}">TXT</a></li>
            </ul>
        </div>
        <div>
            <a href="{% url 'dash:group_dashboard' %}"><button class="mx-2 btn btn-outline-primary">Back</button></a>
        </div>
    </div>
</div>
{% endblock content %}

templates/view/sensor_view.html
{% extends 'base.html' %}

{% block content %}
<div class="m-5">
    {% if messages %}
        <div class="mx-auto alerts">

            {% for message in messages %}
                {% if message.tags == "error" %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% elif message.tags == "info" %}
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% endif %}
            {% endfor %}

        </div>
    {% endif %}

    <div id="tester" style="width:100%;height:250px;"></div>

    <form id="main_form" method="POST">
        {% csrf_token %}
        <span class="fs-2 p-2">Sensor Details</span>
        
        <hr>
        <div class="d-flex flex-column m-3 p-3">
            <div class="d-flex flex-row flex-fill">
                <div class="m-3 flex-fill">
                    <label class="form-label fs-5" for="{{form.sensor_name.id_for_label}}">Sensor Name</label>
                    {{form.sensor_name}}
                </div>
            
                <div class="m-3 flex-fill">
                    <label class="form-label fs-5" for="{{form.sensor_type.id_for_label}}">Sensor Type</label>
                    {{form.sensor_type}}
                </div>
            </div>
            <div class="d-flex flex-row flex-fill">
                <div class="m-3 flex-fill">
                    <label class="form-label fs-5" for="{{form.key.id_for_label}}">API Key</label>
                    {{form.key}}
                </div>
                <div class="m-3 flex-fill">
                    <label class="form-label fs-5" for="{{form.sensor_group.id_for_label}}">Sensor Group</label>
                    {{form.sensor_group}}
                </div>
            </div>
            <div class="d-flex flex-row flex-fill">
                <div class="m-3 flex-fill">
                    <label class="form-label fs-5" for="{{form.sensor_description.id_for_label}}">Sensor Description</label>
                    {{form.sensor_description}}
                </div>
            </div>
        </div>
    </form>
    <div class="d-flex flex-row mt-4 ms-3">
        <div class="btn-group">
            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                Download Data
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'dash:download_data' 'csv' form.key.value%}">CSV</a></li>
                <li><a class="dropdown-item" href="{% url 'dash:download_data' 'txt' form.key.value%}">TXT</a></li>
            </ul>
        </div>
        <div>
            <a href="{% url 'dash:sensor_dashboard' %}"><button class="mx-2 btn btn-outline-primary">Back</button></a>
        </div>
    </div>    
</div>

<script>

    //required variables
    var latest_data = null;
    var main_chart = document.getElementById('tester');
    
    function date_resolver(result){
        console.log(result.dates)
        if (result.dates !=null){
            if(result.dates.length-1 > 0){
                latest_data = result.dates[result.dates.length-1];
            }
        }
    }

    //on load
    $.get({url:'/sensor/data/get/?key={{form.key.value}}&initial=1',success: function(result){
        Plotly.newPlot(main_chart, [{x:result.dates, y: result.datas}], {margin: { t: 0 }});
        date_resolver(result);
    }});

    //on intervals
    setInterval(function(){
        if (latest_data != null){
            $.ajax({url:`/sensor/data/get/?key={{form.key.value}}&initial=0&date=${latest_data}`,success: function(result){
                Plotly.extendTraces(main_chart, {y:[result.datas], x:[result.dates]}, [0])
            }});
        } else {
            $.get({url:'/sensor/data/get/?key={{form.key.value}}&initial=1',success: function(result){
                Plotly.newPlot(main_chart, [{x:result.dates, y: result.datas}], {margin: { t: 0 }});
                date_resolver(result);
            }});
        }
    }, 10000)

</script>
{% endblock content %}