IoT_Dash/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dash.urls'))
]

dash/urls.py
from django.urls import path
from . import views

app_name = 'dash'

urlpatterns = [
    
    #Sensor
    path('sensor/create/', views.sensor_create, name='sensor_create'),
    path('sensor/dashboard/', views.sensor_dashboard, name='sensor_dashboard'),
    path('sensor/view/', views.sensor_view, name='sensor_view'),
    path('sensor/edit/', views.sensor_edit, name='sensor_edit'),
    path('sensor/delete/', views.sensor_delete, name='sensor_delete'),
    path('sensor/data/', views.sensor_data, name='sensor_data'),
    path('sensor/data/get/', views.sensor_get, name='sensor_get'),

    #Sensor Group
    path('group/create/', views.group_create, name='group_create'),
    path('group/dashboard/', views.group_dashboard, name='group_dashboard'),
    path('group/view/', views.group_view, name='group_view'),
    path('group/edit/', views.group_edit, name='group_edit'),
    path('group/delete/', views.group_delete, name='group_delete'),
    
    #Login/Logout
    path('logout/', views.logout_user, name='logout_user'),
    path('', views.login_user, name='login'),

    # Download data
    path('download_data/<str:file_format>/<str:sensor_key>/', views.download_data, name='download_data'),
    path('download_group_data/<str:file_format>/<str:group_id>/', views.download_group_data, name='download_group_data'),
]

templates/base.html
{% load static %}
<head>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.plot.ly/plotly-2.24.1.min.js" charset="utf-8"></script>
</head>

<style>
    .dropdown-item:hover {
        text-decoration: underline;
    }
</style>

<body>
    <div class="d-flex flex-row">
        <div class="p-3 bg-dark text-white" style="min-height: calc(100vh); width: 220px">
            <hr>
            <ul class="nav nav-pills flex-column p-1 mb-auto">
                <li class="p-1">
                    <a href="{% url 'dash:sensor_dashboard' %}" class="text-white text-decoration-none nav-link {% if site_settings.active == 'Sensors' %}active{% endif %}">Sensors</a>
                </li>
                <li class="p-1">
                    <a href="{% url 'dash:group_dashboard' %}" class="text-white text-decoration-none nav-link {% if site_settings.active == 'Sensor_Groups' %}active{% endif %}">Sensor Groups</a>
                </li>
            </ul>
            <hr>
        </div>
        <div class="d-flex flex-column flex-fill bd-highlight">

            <div class="bd-highlight shadow-sm" style="height: 60px;">
                <div class="container-fluid p-2 ">
                    <div class="row">
                        <Span class="fs-3 col-11">{{site_settings.dashboard_heading}}</Span>
                        <div class="dropdown col-1">
                            <button class="dropdown-toggle" style="border: none; background: white" type="button" id="user" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="user">
                            <li><a class="dropdown-item" href="{% url 'dash:logout_user' %}">Logout</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% block content %} {% endblock %}
        </div>    
</body>